[package]
name = "probabilistic-programming"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
csv = "1.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand_distr = "0.4"
itertools = "0.13.0"
